<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="airport.asmxWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/airport.asmxWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/airport.asmxWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://www.webserviceX.NET">
    <import location="http://www.webservicex.net/airport.asmx?WSDL" namespace="http://www.webserviceX.NET"/>
    <plnk:partnerLinkType name="airportSoapLinkType">
        <plnk:role name="airportSoapRole" portType="ns:airportSoap"/>
    </plnk:partnerLinkType>
</definitions>
