<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="CountryInfoRequestorWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/CountryInfoRequestorWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/CountryInfoRequestorWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://j2ee.netbeans.org/wsdl/BpelRESTService/src/CountryInfoRequestor">
    <import location="CountryInfoRequestor.wsdl" namespace="http://j2ee.netbeans.org/wsdl/BpelRESTService/src/CountryInfoRequestor"/>
    <plnk:partnerLinkType name="CountryInfoRequestorLinkType">
        <plnk:role name="CountryInfoRequestorRole" portType="ns:CountryInfoRequestorPortType"/>
    </plnk:partnerLinkType>
</definitions>
